// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpfuisdlextrgnltcbjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwZnVpc2RsZXh0cmdubHRjYmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzIxNzIsImV4cCI6MjA3MjEwODE3Mn0.yVYEuOygNTmy-RS8mVqoNkhGYPEoOmRq_HC86tpHK9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});